apiVersion: v1
kind: Service
metadata:
  name: canary-client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: canary-web
    type: canary
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client-deployment-canary
spec:
  replicas: $CANARY_REPLICAS
  selector:
    matchLabels:
      component: canary-web
      type: canary
  template:
    metadata:
      labels:
        component: canary-web
        type: canary
    spec:
      containers:
        - name: client
          image: sampriyadarshi/multi-client:$BUILD_NUMBER
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: sampriyadarshi/multi-server:$BUILD_NUMBER
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
